package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;

import java.util.LinkedList;

public class ELitTrue extends Expr {

    public ELitTrue() { }

    public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

    @Override
    public boolean evalExpr() {
        return true;
    }

    @Override
    public String returnExprType(LinkedList<Env> env) {
        return "boolean";
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ELitTrue) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }


}
