package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;

import java.util.LinkedList;

public class Empty extends Stmt {

  public Empty() { }

  public <R,A> R accept(Latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

    @Override
    public boolean functionsReturnAchievibility() {
        return false;
    }

    @Override
    public void checkTypes(LinkedList<Env> envs, String currentFunction) {

    }


    public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.Empty) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
