package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;

import java.util.LinkedList;

public class EMul extends Expr {
  public final Expr expr_1, expr_2;
  public final MulOp mulop_;

  public EMul(Expr p1, MulOp p2, Expr p3) { expr_1 = p1; mulop_ = p2; expr_2 = p3; }

  public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

    @Override
    public String returnType(LinkedList<Env> envs) {
        String type1 = expr_1.returnType(envs);
        String type2 = expr_2.returnType(envs);
        if (type1 == type2) return type1;
        return "null";
       // else
         //   throw new IllegalArgumentException("Not compatible operands in line");
    }

    @Override
    public String returnExprType() {
        String expr1Type = expr_1.returnExprType();
        String expr2Type = expr_2.returnExprType();
        if ((expr1Type == expr2Type) && (expr1Type == "int"))
            return "int";
        else
            throw new IllegalArgumentException("Multiplication: invalid operands: " + expr1Type + ", and " + expr1Type);
    }

    public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.EMul) {
      Latte.Absyn.EMul x = (Latte.Absyn.EMul)o;
      return this.expr_1.equals(x.expr_1) && this.mulop_.equals(x.mulop_) && this.expr_2.equals(x.expr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expr_1.hashCode())+this.mulop_.hashCode())+this.expr_2.hashCode();
  }


}
