package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;
import Latte.Exceptions.TypeException;

public class ERel extends Expr {
    public final Expr expr_1, expr_2;
    public final RelOp relop_;

    public ERel(Expr p1, RelOp p2, Expr p3) { expr_1 = p1; relop_ = p2; expr_2 = p3; }

    public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) throws TypeException { return v.visit(this, arg); }

    @Override
    public String returnExprType(Env env, String currentFunction) throws TypeException {
        String expr1Type = expr_1.returnExprType(env, currentFunction);
        String expr2Type = expr_2.returnExprType(env, currentFunction);
        if (expr1Type == expr2Type)
            return "boolean";
        else
            throw new TypeException(currentFunction,
                    "\n\t\tAt relation expression: invalid operands: " + expr1Type + ", and " + expr2Type);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ERel) {
            Latte.Absyn.ERel x = (Latte.Absyn.ERel)o;
            return this.expr_1.equals(x.expr_1) && this.relop_.equals(x.relop_) && this.expr_2.equals(x.expr_2);
        }
        return false;
    }

    public int hashCode() {
        return 37*(37*(this.expr_1.hashCode())+this.relop_.hashCode())+this.expr_2.hashCode();
    }


}
