package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;
import Latte.Exceptions.TypeException;

public class EVar extends Expr {
    public final String ident_;

    public EVar(String p1) { ident_ = p1; }

    public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) throws TypeException { return v.visit(this, arg); }

    @Override
    public String returnExprType(Env env, String currentFunction) {
        return env.variableType.get(ident_);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.EVar) {
            Latte.Absyn.EVar x = (Latte.Absyn.EVar)o;
            return this.ident_.equals(x.ident_);
        }
        return false;
    }

    public int hashCode() {
        return this.ident_.hashCode();
    }

}
