package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;

import java.util.LinkedList;

public class FnDef extends TopDef {
    public final Type type_;
    public final String ident_;
    public final ListArg listarg_;
    public final Block block_;

    public FnDef(Type p1, String p2, ListArg p3, Block p4) { type_ = p1; ident_ = p2; listarg_ = p3; block_ = p4; }

    public <R,A> R accept(Latte.Absyn.TopDef.Visitor<R,A> v, A arg) {
        return v.visit(this, arg);
    }

    @Override
    public void returnType() {
        Env.functionsReturnType.put(ident_, type_.toString());
        Env.functionsReturnAchievibility.put(ident_, block_.functionsReturnAchievibility());
    }

    @Override
    public void checkTypes(LinkedList<Env> envs) {
        block_.checkTypes(envs, ident_);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.FnDef) {
            Latte.Absyn.FnDef x = (Latte.Absyn.FnDef)o;
            return this.type_.equals(x.type_) && this.ident_.equals(x.ident_) && this.listarg_.equals(x.listarg_) && this.block_.equals(x.block_);
        }
        return false;
    }
    
    public String toString(){
        return "; Definicja funkcji: "+type_ + " " + ident_ + " " + listarg_ + " " + block_;
    }

    public int hashCode() {
        return 37*(37*(37*(this.type_.hashCode())+this.ident_.hashCode())+this.listarg_.hashCode())+this.block_.hashCode();
    }


}
