package Latte.Absyn; // Java Package generated by the BNF Converter.

public class GE extends RelOp {

    public GE() { }

    public <R,A> R accept(Latte.Absyn.RelOp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

    @Override
    public String getMnemonic() {
        return "jge";
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.GE) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }


}
