package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;

import java.util.LinkedList;

public abstract class Item implements java.io.Serializable {
  public abstract <R,A> R accept(Item.Visitor<R,A> v, A arg);

    public abstract String getIdent();

    public void checkTypes(LinkedList<Env> envs, String currentFunction, Type type_) {
        Env env = envs.getLast();
        env.variableType.put(this.getIdent(), type_.toString());
    }

    public interface Visitor <R,A> {
    public R visit(Latte.Absyn.NoInit p, A arg);
    public R visit(Latte.Absyn.Init p, A arg);

  }

}
