package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;
import Latte.Exceptions.TypeException;

import java.util.LinkedList;

public abstract class Item implements java.io.Serializable {
    public abstract <R,A> R accept(Item.Visitor<R,A> v, A arg);

    public abstract String getIdent();

    public void checkTypes(LinkedList<Env> envs, String currentFunction, Type type_) throws TypeException {
        Env env = envs.getLast();

        if (env.varDeclarationEnv.containsKey(this.getIdent()))
            if (env.varDeclarationEnv.get(this.getIdent())== envs.size())
                throw new TypeException(currentFunction, "\n\t\t At variable " + this.getIdent() + " declaration: " 
                        + "variable " + this.getIdent() + " is redeclared.");

        env.variableType.put(this.getIdent(), type_.toString());
        env.varDeclarationEnv.put(this.getIdent(), envs.size());

    }

    public interface Visitor <R,A> {
        public R visit(Latte.Absyn.NoInit p, A arg);
        public R visit(Latte.Absyn.Init p, A arg);

    }

}
