package Latte.Absyn; // Java Package generated by the BNF Converter.

public class LTH extends RelOp {

  public LTH() { }

  public <R,A> R accept(Latte.Absyn.RelOp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

    @Override
    public String getMnemonic() {
        return null;
    }

    public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.LTH) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
