package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Exceptions.TypeException;

public abstract class TopDef implements java.io.Serializable {
    public abstract <R,A> R accept(TopDef.Visitor<R,A> v, A arg) throws TypeException;


    public interface Visitor <R,A> {
        public R visit(Latte.Absyn.FnDef p, A arg) throws TypeException;

    }

}
