package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;
import Latte.Exceptions.TypeException;

import java.util.LinkedList;

public abstract class TopDef implements java.io.Serializable {
    public abstract <R,A> R accept(TopDef.Visitor<R,A> v, A arg);
    public abstract void returnType();

    public abstract void checkTypes(LinkedList<Env> envs) throws TypeException;

    public interface Visitor <R,A> {
        public R visit(Latte.Absyn.FnDef p, A arg);

    }

}
