package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;
import Latte.Exceptions.TypeException;

public class VRet extends Stmt {

    public VRet() { }

    public <R,A> R accept(Latte.Absyn.Stmt.Visitor<R,A> v, A arg) throws TypeException { return v.visit(this, arg); }

    @Override
    public boolean functionsReturnAchievibility() {
        return true;
    }

    @Override
    public void checkTypes(Env env, String currentFunction) throws TypeException {
        if (Env.functionsReturnType.get(currentFunction) != "void")
            throw new TypeException(currentFunction,
                    "\n\t\tAt return void statement: cannot return void to non-void return function.");
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.VRet) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

}
