package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Env;

import java.util.LinkedList;

public class VRet extends Stmt {

    public VRet() { }

    public <R,A> R accept(Latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

    @Override
    public boolean functionsReturnAchievibility() {
        return true;
    }

    @Override
    public void checkTypes(LinkedList<Env> envs, String currentFunction) {
        if (Env.functionsReturnType.get(currentFunction) != "void")
            throw new IllegalArgumentException(currentFunction.toUpperCase() + " function: cannot return void to non-void function.");
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.VRet) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

}
